import { Format } from "./format";

export const dotnet: Format = {
  "day-of-month-1": "d",
  "day-of-month-2": "dd",
  "day-of-week-abbr": "ddd",
  "day-of-week": "dddd",
  "month-1": "M",
  "month-2": "MM",
  "month-name-abbr": "MMM",
  "month-name": "MMMM",
  "year-2": "yy",
  "year-4": "yyyy",
  "am-pm": "tt",
  "time-12h-1": "h",
  "time-12h-2": "hh",
  "time-24h-1": "H",
  "time-24h-2": "HH",
  "minutes-1": "m",
  "minutes-2": "mm",
  "seconds-1": "s",
  "seconds-2": "ss",
  "milliseconds-3": "fff",
  "timezone-1": "z",
  "timezone-4": "zzz",
};
